[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "matfonter"
version = "0.1.0"
description = "A tiny font helper for applying font files to matplotlib."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
  { name = "pylorsun", email="pylorsun500@outlook.com" }
]
dependencies = [
  "matplotlib>=3.7"
]
keywords = ["matplotlib", "font", "ttf", "plot", "visualization"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Visualization"
  "Framework :: Matplotlib"
  "License :: OSI Approved :: MIT License"
]
license-files = ["LICENSE"]

[tool.setuptools]
packages = ["matfonter"]

[project.urls]
GitHub = "https://github.com/PylorSun500/matfonter"
Issue = "https://github.com/PylorSun500/matfonter/issues"
